"""Provide description validator components for the application."""

def validate_description(description: str) -> str:
    """
    Validate and clean the description generated by Qwen.
    """

    if description is None:
        raise ValueError("Qwen returned no description")

    description = description.strip()

    if not description:
        raise ValueError("Qwen returned an empty description")

    if len(description) < 10:
        raise ValueError(
            "Qwen returned an invalid or very short description"
        )

    return description
