"""add OCR confidence and word count

Revision ID: b9c3faf18f12
Revises: 41cb63f792f5
Create Date: 2026-09-08 18:04:49.982265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c3faf18f12'
down_revision: Union[str, Sequence[str], None] = '41cb63f792f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_analyses', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    op.add_column('image_analyses', sa.Column('ocr_word_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_analyses', 'ocr_word_count')
    op.drop_column('image_analyses', 'ocr_confidence')
    # ### end Alembic commands ###
