"""add document analysis fields

Revision ID: bda74224afaa
Revises: b9c3faf18f12
Create Date: 2026-09-22 14:06:30.191308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda74224afaa'
down_revision: Union[str, Sequence[str], None] = 'b9c3faf18f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_analyses', sa.Column('decisions', sa.JSON(), nullable=True))
    op.add_column('document_analyses', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('document_analyses', sa.Column('section_count', sa.Integer(), nullable=True))
    op.add_column('document_analyses', sa.Column('chunk_summaries', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_analyses', 'chunk_summaries')
    op.drop_column('document_analyses', 'section_count')
    op.drop_column('document_analyses', 'chunk_count')
    op.drop_column('document_analyses', 'decisions')
    # ### end Alembic commands ###
